### PR TITLE
enrichments to reader's experience with distributed sharding doc.

### PR DESCRIPTION
**Pull request by mattall**
Corrected some things for readability. I took out a few commas where
they didn’t appear necessary. I also attempted to improve the ‘flow’ by
making complete sentences out of some parts (line 28). For some reason
though the JSON formatting got messed up (lines 33 to 56).

### CODE REVIEW

**Comment by lvca** [comment]
Awesome, thanks.

**Comment by mattall** [comment]
I also made up a log of questions/comments/suggestions that I didn't add. Where is the appropriate place for sharing these?

**Comment by lvca** [comment]
Here as comments

**Comment by mattall** [comment]
Sharding Changes Log, Matthew Hall. 
August 2, 2016:

questions: 

	In the example for multiple servers per cluster: 
It’s unclear what ‘default one’ means. Does this mean default configuration or something else?  
	“- `client_china`, will be managed by all of the nodes (it would be equivalent as writing `“<NEW_NODE>”`, see cluster "*", the default one)”
		
	Does node generally mean server/machine? 

	“OrientDB automatically creates a new cluster per each class as soon as a node joins the distributed cluster.” Is this a statement about data-replication or scaling? Does this mean that if I link a new server to my database, that it is now a cluster?

When a node goes down, the [clusters](Concepts.md#cluster) where the node was master are reassigned to other servers.

In cluster locality… “If you want to permanently change the mastership of a [cluster](Concepts.md#cluster), rename the cluster by changing it’s suffix to that of the node you want assign as master.“ An example might help illustrate this concept. In the use case with Client having three clusters (USA, Europe, and China) .. If I do … update client_usa.name = client_asia …  Does Server_USA master any clusters? Is the data kept at servers USA and China shuffled around at all or do they both keep the same exact records after the update?

Under limitations…  “1. If `hotAlignment=false` is set, when a node re-joins the cluster (after a failure or simply unreachability) the full copy of database from a node could have no all information about the shards.” 
	Do you mean to say “the full copy of a  database from a node could be missing information about the shards” or “the full copy of the database from a node could have no information about the shards.”? 

	Can this limitation be removed from the list? 
	1. Hot change of distributed configuration not available. This will be introduced at release 2.0 via command line and in visual way in the Workbench of the Enterprise Edition (commercial licensed)

comments: 
	In configuration use case : I switched parenthesis and brackets to fix the link. “(Multiple servers per cluster)[Distributed-Sharding.md#Multiple-servers-per-cluster] use case:”

Suggestions: 
	Add a link to cluster selection strategy (css) in the cluster locality section.This will help differentiate “local” from other css. (This was pulled)

**Pull request merged**
