### PR TITLE
Getting started section finished.

### PR DESCRIPTION
**Pull request by smolinari**

### CODE REVIEW

**Comment by lvca** [comment]
Super!

**Comment by lvca** [comment]
I've tried to generate the static book but it gives me hundreds of 

```
warn: page SQL-Where.md contains an hyperlink to resource outside spine "SQL-Traverse.md"
warn: page SQL-Where.md contains an hyperlink to resource outside spine "SQL-Traverse.md"
warn: page Schema.md contains an hyperlink to resource outside spine "SQL-Alter-Property.md"
warn: page Sequences-and-auto-increment.md contains an hyperlink to resource outside spine "SQL-Create-Sequence.md"
warn: page Sequences-and-auto-increment.md contains an hyperlink to resource outside spine "SQL-Alter-Sequence.md"
warn: page Sequences-and-auto-increment.md contains an hyperlink to resource outside spine "SQL-Drop-Sequence.md"
warn: page Studio-Schema.md contains an hyperlink to resource outside spine "SQL-Alter-Class.md"
warn: page Tutorial-Classes.md contains an hyperlink to resource outside spine "SQL-Create-Class.md"
warn: page Tutorial-Classes.md contains an hyperlink to resource outside spine "SQL-Create-Class.md"
warn: page Tutorial-Classes.md contains an hyperlink to resource outside spine "SQL-Create-Property.md"
warn: page Tutorial-Classes.md contains an hyperlink to resource outside spine "SQL-Alter-Property.md"
warn: page Tutorial-Clusters.md contains an hyperlink to resource outside spine "SQL-Alter-Class.md"
warn: page Tutorial-Clusters.md contains an hyperlink to resource outside spine "SQL-Alter-Class.md"
warn: page Tutorial-Java.md contains an hyperlink to resource outside spine "SQL-Create-Vertex.md"
warn: page Tutorial-Java.md contains an hyperlink to resource outside spine "SQL-Delete-Vertex.md"
warn: page Tutorial-Working-with-graphs.md contains an hyperlink to resource outside spine "SQL-Create-Vertex.md"
warn: page Tutorial-Working-with-graphs.md contains an hyperlink to resource outside spine "SQL-Create-Vertex.md"
warn: page Tutorial-Working-with-graphs.md contains an hyperlink to resource outside spine "SQL-Delete-Vertex.md"
warn: page Tutorial-Working-with-graphs.md contains an hyperlink to resource outside spine "SQL-Create-Edge.md"
warn: page Tutorial-Working-with-graphs.md contains an hyperlink to resource outside spine "SQL-Delete-Edge.md"
info: generation is finished
```

**Comment by lvca** [comment]
I can't find why

**Comment by kennethpjdyer** [comment]
Getting the same here.  It's weird cause the link resources are written correctly.

**Comment by lvca** [comment]
Found: 3rd level had more level of identity. restoring to the 3rd did the job. Committing now...

**Comment by kennethpjdyer** [comment]
Tested here.  Works fine again.

**Comment by lvca** [comment]
Hey @smolinari your summary is online ;-) Thank you.

**Comment by smolinari** [comment]
Your welcome. I am glad I could help. More to come! :smile:

Scott

**Pull request merged**
