### PR TITLE
Update OrientJS-Database.md

### PR DESCRIPTION
**Pull request by GabCamarda**
Going through the documentation, I've seen a few mispelt words and I wanted to correct them - hope it's ok.
I've noticed a few more in other pages, I'd propose a change when I see them.

### CODE REVIEW

**Comment by kennethpjdyer** [comment]
Thanks!

**Comment by lvca** [comment]
Hey @kennethpjdyer are you taking care of cherry-picking those commits to the 3.0 branch?

**Comment by kennethpjdyer** [comment]
Didn't know about cherry-picking, but I do now.  Fixes on both are now in master.

**Comment by lvca** [comment]
Thanks, in this way the new 3.0 is not "old" ;-)

**Pull request merged**
