### PR TITLE
Proofread Graph-Consistency.md and changed min required Java to 1.8

### PR DESCRIPTION
**Pull request by smolinari**

### CODE REVIEW

**Comment by lvca** [comment]
Thank you

**Comment by smolinari** [comment]
Was the Java version update correct? Just want to be sure, as that is a big jump and requirement. 

Scott

**Comment by lvca** [comment]
1.7 is enough.

**Comment by smolinari** [comment]
Hmm..I can't find the issue, and I could swear I related it back to this PR, but the thread was noting code in ODB was Java 8 specific, and thus the required the minimum version should be 8. If that is wrong, I need to make a correction.

Scott

**Comment by lvca** [comment]
I already changed the version, the rest of your PR was good ;-)

**Comment by smolinari** [comment]
Ah. Ok. Great. :+1: 

Scott

**Comment by smolinari** [comment]
Steps to replicate. 

1. go to the docs and use the search for transactions.
2. close the browser window.
3. go back to the docs.
4. click into one of the sections in the navigation

Expected. 

No search values in the search. Navigation works normally.

What actually happens?

Search value is still there (upper left) and messes up the navigation (some of the sections are missing).

Scott

**Comment by smolinari** [comment]
@lvca -Hey Luca. About the Java version, I ran into this today. 

https://github.com/orientechnologies/orientdb/issues/4923

The author of the other issue related to this issue mentioned there is Java 1.8 specific code in OrientDB. So it seems, using anything less than Java 1.8 breaks ODB? `Map.putIfAbsent` is Java 1.8 specific? 

Scott

**Comment by robfrank** [comment]
Hi scott, use of java8 code was a bug (fixed); the code is java7 compliant. 
But it runs well even in java8.

**Comment by smolinari** [comment]
Ok. So, that problem is solved through changes in the code, and not through the user having to upgrade. That is good to hear. Maybe someone from the team could update those issues? 

Scott

**Pull request merged**
