### PR TITLE
Add docs for lazy detach

### PR DESCRIPTION
**Pull request by wouterv**
Docs for https://github.com/orientechnologies/orientdb/issues/4032

### CODE REVIEW

**Comment by lvca** [comment]
Super, thanks!

**Comment by laa** [comment]
tests are failing after this merge I revert it.

**Comment by wouterv** [comment]
There are tests run on documentation? How can I do this myself?

**Comment by laa** [comment]
run mvn clean install

**Comment by wouterv** [comment]
@laa  You are commenting on an orientdb *Documentation* pull request... 
Perhaps you meant to be commenting on https://github.com/orientechnologies/orientdb/pull/4769?

If so, I have ran mvn clean install locally before I created the pull request and it was ok.
Also github showed that an automated build also turned out fine. 

Previously I got emails whenever a build failed after a merge, but I haven't received it, so I am curious about the problem you are experiencing.

**Comment by laa** [comment]
Hi,
I am sorry I commented wrong push. Your code changes are OK.

**Pull request merged**
