### PR TITLE
Wrapped quotes around the ISO8601 date format

### PR DESCRIPTION
**Pull request by jeremysnyder**
Wrapped quotes around the date format so that it can be executed as shown.

### CODE REVIEW

**Comment by luigidellaquila** [comment]
Merged, thanks!

**Comment by lvca** [comment]
@luigidellaquila could you please cherry-pick it to 2.2 too? Thanks.

**Comment by luigidellaquila** [comment]
Sure, doing it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Done on both 2.2.x and 3.0.x

**Pull request merged**
