### PR TITLE
Update NET.md

### PR DESCRIPTION
**Pull request by realityenigma**
Updated documentation to reflect the existence of the alpha .NET SDK under development.

### CODE REVIEW

**Comment by kennethpjdyer** [comment]
Thanks!

**Comment by lvca** [comment]
@kennethpjdyer are you keeping update both 2.2.x and 3.0 branches with this PRs?

**Comment by kennethpjdyer** [comment]
Taken care of.

**Comment by realityenigma** [comment]
Thanks!

**Pull request merged**
