### PR TITLE
Various minor changes:

### PR DESCRIPTION
**Pull request by mbhulin**
Creation of new database only possible in plocal or memory mode
Non-transactional graph for schema definition.
Redirect internal link: internal link instead of link to wiki.
Minor typo corrections.
Inserted: Link to prepared queries.

### CODE REVIEW

**Comment by lvca** [comment]
@mbhulin Thanks or the contribution. Please could you sign the claub Apache license for contribution?

**Comment by mbhulin** [comment]
O.k. Do I have to sign it for every change? I thought that having signed it two weeks ago for another update of the documentation is sufficient for future changes of orientdb-docs.

**Comment by lvca** [comment]
Just once per repository. Maybe you signed the one in orientdb repo.

**Comment by lvca** [comment]
Merged, thanks!

**Pull request merged**
