### PR TITLE
Data modeling section refactor

### PR DESCRIPTION
**Pull request by smolinari**
Please have a look at it first. If the TOC is ok. 

https://smolinari.gitbooks.io/orientdb-documentation/content/v/040d58ffdf023e94f5fcdb6104749e727600ee16/index.html

Scott

### CODE REVIEW

**Comment by lvca** [comment]
Seems 6.1.21 (SQL DELETE) is missing. The rest seems perfect. If you could update the missing UPDATE I can merge immediately. Thank you.

**Comment by smolinari** [comment]
Good catch. Looks like the file "Console-Command-Delete.md" is missing out of this repo too. That is the problem. Can someone add it again?

Scott

**Comment by lvca** [comment]
I thought we removed console CRUD commands: are a duplication of console commands.

**Comment by smolinari** [comment]
I have no idea. Should I just delete the entry in the TOC?

Scott

**Comment by lvca** [comment]
They should stay, but pointing to the SELECT, UPDATE, DELETE and INSERT sql pages.

**Comment by smolinari** [comment]
I did this a bit differently. Linking to SQL-Delete.md would take the user out of the commands section, when they click on the command, which wouldn't make much sense for the user. So, I took the text from that file and created the missing file.

Scott

**Comment by lvca** [comment]
Thanks.

**Comment by lvca** [comment]
Thanks you!

**Comment by lvca** [comment]
Uploading the new docs...

**Pull request merged**
